apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: tms-app
spec:
  selector:
    app: task-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
